# -*- coding: utf-8 -*-
"""POKEDEX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HLQcVGbKSrwDnlThadxzbYm6HSOCBWb
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
df=pd.read_csv("/content/pokedex.csv", sep=",")

lista_borrar=['japanese_name','german_name', 'abilities_number', 'ability_1',	'ability_2',
              'ability_hidden','catch_rate', 'base_friendship','base_experience', 'growth_rate','egg_type_number', 'egg_type_1', 'egg_type_2',
              'percentage_male', 'egg_cycles']
df.drop(lista_borrar, axis="columns", inplace=True)
df.drop(df.columns[df.columns.str.contains('unnamed', case=False)], axis=1, inplace=True) # ACA BORRE EL UNNAMED :D
df_new=df.set_index('pokedex_number') # ACA BORRE LOS NUMEROS DE INDICE Y CONVERTI LA COLUMNA pokedex_number COMO INDICE :DD
index=df_new.index.names=['pokechota']
df_new.head()


#-----------CON ESTO CAMBIO LA INICIAL A MAYUSCULA DE TODOS LOS ARCHIVOS DE LA CARPETA-----#
#path = '/content/imagespoke/'                                                             #|    
                                                                                          #|
#for file in os.listdir(path):                                                             #|
#    os.rename(path + file, path + file.capitalize())                                      #|  
                                                                                          #|  
#then = os.listdir(path)                                                                   #|  
#print(then)                                                                               #|    
                                                                                          #|                                                                                              
#------------------------------------------------------------------------------------------
df_new.head()

lista_datos=[]
def crear_lista(*args):
  while True:
    datos=input("Ingrese los datos de los pokémon: ")
    if datos=="salir":
      break
    lista_datos.append(datos)
  print(lista_datos)
  
  
def mostrar(*args):
  h_value=int(input("Ingrese la cantidad de datos que quiere visualizar: "))
  df_mostrar=df_new[lista_datos].head(h_value)
  return df_mostrar

crear_lista()
mostrar()

# librería + tipo de gráfico + (valores de x, valores de y)
import random as random
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd',
          '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'darkred','size':15}

plt.figure(figsize=(12,8))
x_v= df_new['name'].head()
y_v= df_new['attack'].head()
plt.bar(x_v,y_v, color=colors)
plt.xlabel("Pokémon", fontdict=font1)
plt.ylabel("Attack Damage", fontdict=font2)
plt.show()

import numpy as np
import re
import os
from IPython.display import display, Image
import pathlib

# Saco los against asi se ve mas comodo el detalle del pokemon
against=['against_normal', 'against_fire', 'against_water', 'against_electric', 'against_grass', 'against_ice', 'against_fight', 'against_poison', 'against_ground', 'against_flying', 'against_psychic', 'against_bug', 'against_rock', 'against_ghost', 'against_dragon', 'against_dark', 'against_steel', 'against_fairy']
df_new.drop(against, axis='columns', inplace=True) 

def general_info(*args):
  poki=input('Nombre del pokemon: ')

  print(poki.capitalize())
  if poki.capitalize() in df_new.name.values:
    #poki in df_new.name.values # Si existe en la columna name...
    print(df_new.loc[df_new['name'] == poki.capitalize()])

    #------CONCATENO LA RUTA DE LA CARPETA CON LA VARIABLE POKI Y .PNG-----
    folder_string ="/content/imagespoke/"
    file_string=poki.capitalize()
    png=".png"
    file_png=file_string+png
    path_string=folder_string+file_png
    if file_png in path_string:
      display(Image(filename=path_string)) 
      

general_info()

from IPython.display import display, Image
display(Image(filename='/content/sample_data/imagespoke/abra.png'))

team=[]
def crear_team(*args):
  caca=0
  while caca<6:
    poke=input("Ingrese nombre de pokémon: ")
    if poke in df_new.name.values:
      team.append(poke)
      caca+=1
    else:
      print('Nope')
  print(team)

crear_team()

